### ISSUE TITLE
how to define an array of array of number/string (2d array)?

### ISSUE THREAD

**Issue by grimmer0125** [BetterCallSky/ts-mongoose#40]
Thanks for supplying this so great library. 

in normal mongoose
I can define like this 
```
const blogSchema = new Schema({
    data: [[Number]]
});
```
How can I define this in ts-mongoose?

**Comment by lchimaru** [comment]
Following seems to be working:
```ts
Type.array({ required: true }).of(Type.array({ required: true }).of(Type.string())),
```
Also this:
```ts
Type.array().of(Type.array().of(Type.string())),
```

What type is returned for `data`?

**Comment by grimmer0125** [comment]
Thanks. @lchimaru . 

It just throws a runtime exception 
```
/Users/grimmer/git/v2/server/node_modules/mongoose/lib/schema.js:946
        throw new TypeError('Invalid schema configuration: ' +
              ^
source-map-support.js:441
TypeError: Invalid schema configuration: `undefined` is not a valid type within the array `data`.See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (/Users/grimmer/git/v2/server/node_modules/mongoose/lib/schema.js:946:15)
    at Schema.path (/Users/grimmer/git/v2/server/node_modules/mongoose/lib/schema.js:677:27)
    at Schema.add (/Users/grimmer/git/v2/server/node_modules/mongoose/lib/schema.js:516:14)
    at new Schema (/Users/grimmer/git/v2/server/node_modules/mongoose/lib/schema.js:129:10)
    at Object.exports.createSchema (/Users/grimmer/git/v2/server/node_modules/ts-mongoose/createSchema.js:5:12)
    at Object.<anonymous> (/Users/grimmer/git/v2/server/service/mongoose/User.ts:12:5)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Module.m._compile (/Users/grimmer/git/v2/server/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/grimmer/git/v2/server/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)

```

**Comment by yejimeiming** [comment]
The following writing method can works!

```diff
- Type.array().of(Type.array().of(Type.string()))
+ Type.array().of({})
```

My db data.

<img width="198" alt="image" src="https://github.com/lstkz/ts-mongoose/assets/135394392/c10d59ec-bb1c-47f4-9f72-30314f9e7cef">
